import { NextResponse } from "next/server";
import { createSessionToken, getCurrentHospital, hospitalDestination, SESSION_COOKIE, sessionCookieOptions, validRequestOrigin } from "@/lib/auth";
import { getHospitalById } from "@/lib/db";
import { createPublicSessionToken, getCurrentPublicUser, PUBLIC_SESSION_COOKIE, publicDestination, publicSessionCookieOptions } from "@/lib/public-auth";
import { getPublicUserById } from "@/lib/public-db";
import { verifyEmailCode, type VerificationAccountType } from "@/lib/verification";

export const runtime="nodejs";
export async function POST(request:Request){if(!validRequestOrigin(request))return NextResponse.json({error:"Invalid request origin."},{status:403});try{const body=await request.json();const accountType:VerificationAccountType=body.accountType==="public"?"public":"hospital";const code=String(body.code||"").trim();if(accountType==="public"){const profile=await getCurrentPublicUser();if(!profile)return NextResponse.json({error:"Authentication required."},{status:401});const result=await verifyEmailCode("public",profile.id,code);if(!result.ok)return NextResponse.json({error:result.error},{status:400});const user=await getPublicUserById(profile.id);if(!user)throw new Error("Account not found");const response=NextResponse.json({redirectTo:publicDestination({...user,emailVerifiedAt:result.verifiedAt})});response.cookies.set(PUBLIC_SESSION_COOKIE,await createPublicSessionToken(user,user.tokenVersion),publicSessionCookieOptions);return response;}const profile=await getCurrentHospital();if(!profile)return NextResponse.json({error:"Authentication required."},{status:401});const result=await verifyEmailCode("hospital",profile.id,code);if(!result.ok)return NextResponse.json({error:result.error},{status:400});const hospital=await getHospitalById(profile.id);if(!hospital)throw new Error("Account not found");const response=NextResponse.json({redirectTo:hospitalDestination({...hospital,emailVerifiedAt:result.verifiedAt})});response.cookies.set(SESSION_COOKIE,await createSessionToken(hospital,hospital.tokenVersion),sessionCookieOptions);return response;}catch(error){console.error("Email verification failed",error);return NextResponse.json({error:"Email verification is temporarily unavailable."},{status:500});}}
