"use client";
import { LoaderCircle,ShieldAlert,ShieldCheck,UserRoundCheck } from "lucide-react";
import { useState } from "react";
import { readApiResponse } from "@/lib/client-api";
import type { PublicUserProfile } from "@/lib/types";

export function AdminPublicUserList({initialUsers}:{initialUsers:PublicUserProfile[]}){
  const[users,setUsers]=useState(initialUsers);const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState("");
  async function unblock(id:string){setBusy(id);setMessage("");try{const response=await fetch(`/api/admin/public-users/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"unblock"})});await readApiResponse<{user:PublicUserProfile}>(response,"hospital");setUsers((current)=>current.filter((user)=>user.id!==id));setMessage("Public account unblocked. Its previous session was revoked and the user must sign in again.");}catch(error){setMessage(error instanceof Error?error.message:"Account review failed.");}finally{setBusy(null);}}
  return <section className="mt-10"><div className="mb-4"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-amber-300"><ShieldAlert className="size-4"/> Anti-spam review</p><h2 className="mt-2 text-2xl font-semibold text-white">Blocked public accounts</h2><p className="mt-1 text-sm text-slate-400">Review accounts automatically paused after suspicious repeated medical searches.</p></div>{message&&<p role="status" className="mb-4 rounded-xl border border-cyan-300/15 bg-cyan-300/[.06] p-3 text-sm text-cyan-100">{message}</p>}<div className="space-y-3">{users.map((user)=><article key={user.id} className="panel flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-amber-300/10 text-amber-300"><ShieldAlert/></span><div><strong className="text-white">{user.name}</strong><p className="mt-1 text-sm text-slate-400">{user.email} · {user.phone}</p><p className="mt-1 text-xs text-amber-100/80">{user.blockedReason||"Automated search protection"}{user.blockedAt?` · ${new Date(user.blockedAt).toLocaleString("en-PK")}`:""}</p></div></div><button disabled={busy===user.id} onClick={()=>void unblock(user.id)} className="secondary-btn border-emerald-300/20 text-emerald-200">{busy===user.id?<LoaderCircle className="animate-spin"/>:<UserRoundCheck/>} Restore access</button></article>)}{!users.length&&<div className="panel p-8 text-center text-sm text-slate-400"><ShieldCheck className="mx-auto mb-3 size-7 text-emerald-300"/>No public accounts are awaiting security review.</div>}</div></section>;
}
