"use client";
import Link from "next/link";
import { Building2, LoaderCircle, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

const fields=[
  ["hospitalName","Hospital name","e.g. Mayo Hospital","text"],["licenseNumber","Registration / license number","Official license number","text"],
  ["officialEmail","Official hospital email","admin@hospital.org","email"],["phone","Hospital phone","+92 42 0000000","tel"],
  ["city","City","Lahore","text"],["adminName","Authorized administrator","Full legal name","text"],["adminTitle","Administrator designation","Medical Director / IT Administrator","text"],
] as const;

export function SignupForm(){const router=useRouter();const[pending,setPending]=useState(false);const[error,setError]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");const form=new FormData(event.currentTarget);const payload=Object.fromEntries(form.entries());if(payload.password!==payload.confirmPassword){setError("Passwords do not match.");setPending(false);return;}try{const response=await fetch("/api/auth/signup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error);router.push(result.redirectTo||"/verify-email");}catch(e){setError(e instanceof Error?e.message:"Application could not be submitted.");}finally{setPending(false);}}
return <form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2">{fields.map(([name,label,placeholder,type])=><label key={name} className="auth-field"><span>{label}</span><div><Building2/><input name={name} type={type} required placeholder={placeholder}/></div></label>)}<label className="auth-field"><span>Hospital type</span><div><select name="hospitalType" required defaultValue=""><option value="" disabled>Select type</option><option>Public Hospital</option><option>Private Hospital</option><option>Teaching Hospital</option><option>Specialized Hospital</option></select></div></label><label className="auth-field"><span>Registration authority</span><div><select name="registrationAuthority" required defaultValue=""><option value="" disabled>Select authority</option><option>Punjab Healthcare Commission</option><option>Pakistan Medical & Dental Council</option><option>PHOTA</option><option>Government Health Department</option></select></div></label><label className="auth-field sm:col-span-2"><span>Complete hospital address</span><div><textarea name="address" required rows={3} placeholder="Street, area, district and postal code"/></div></label><label className="auth-field"><span>Create password</span><div><input name="password" type="password" autoComplete="new-password" required minLength={10} placeholder="10+ chars, upper/lowercase and number"/></div></label><label className="auth-field"><span>Confirm password</span><div><input name="confirmPassword" type="password" autoComplete="new-password" required minLength={10} placeholder="Repeat password"/></div></label></div><div className="flex gap-3 rounded-xl border border-cyan-300/15 bg-cyan-300/[.05] p-4 text-xs leading-5 text-slate-300"><ShieldCheck className="size-5 shrink-0 text-cyan-300"/><p>Submitting this form does not grant immediate access. PHOTA administrators must verify the hospital license and official details first.</p></div>{error&&<p role="alert" className="rounded-xl border border-rose-300/20 bg-rose-300/8 p-3 text-sm text-rose-200">{error}</p>}<button disabled={pending} className="auth-submit">{pending?<LoaderCircle className="animate-spin"/>:<ShieldCheck/>}{pending?"Submitting securely…":"Submit hospital application"}</button><p className="text-center text-sm text-slate-400">Already registered? <Link href="/login" className="font-semibold text-emerald-300">Sign in</Link></p></form>}
