import { redirect } from "next/navigation";
import Link from "next/link";
import { Building2, Clock3, CircleAlert, ShieldCheck } from "lucide-react";
import { getCurrentHospital } from "@/lib/auth";
import { LogoutButton } from "@/components/LogoutButton";
import { emailVerificationIsCurrent } from "@/lib/verification";
export const dynamic="force-dynamic";
export default async function PendingPage(){const hospital=await getCurrentHospital();if(!hospital)redirect("/login");if(!emailVerificationIsCurrent(hospital.emailVerifiedAt))redirect("/verify-email");if(hospital.role==="admin")redirect("/admin/hospitals");if(hospital.verificationStatus==="verified")redirect("/workspace");const rejected=hospital.verificationStatus==="rejected";return <main className="auth-page grid min-h-screen place-items-center px-4 py-10"><section className="w-full max-w-2xl rounded-[30px] border border-white/10 bg-[#071014]/90 p-6 text-center shadow-2xl backdrop-blur-xl sm:p-10"><span className={`mx-auto grid size-16 place-items-center rounded-2xl ${rejected?"bg-rose-300/10 text-rose-300":"bg-amber-300/10 text-amber-300"}`}>{rejected?<CircleAlert className="size-8"/>:<Clock3 className="size-8"/>}</span><p className="mt-6 text-xs font-bold uppercase tracking-[.2em] text-slate-500">Hospital verification</p><h1 className="mt-2 text-3xl font-semibold text-white">{rejected?"Application needs attention":"Verification in progress"}</h1><p className="mx-auto mt-4 max-w-lg leading-7 text-slate-400">{rejected?"This hospital application was not approved. Contact PHOTA with corrected registration documents before applying again.":"Your account is secure, but medical workspace access remains locked until a PHOTA administrator verifies the hospital license."}</p><div className="mt-7 grid gap-3 rounded-2xl border border-white/8 bg-white/[.03] p-5 text-left sm:grid-cols-2"><Detail icon={<Building2/>} label="Hospital" value={hospital.hospitalName}/><Detail icon={<ShieldCheck/>} label="License" value={hospital.licenseNumber}/></div><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/profile" className="secondary-btn">View hospital profile</Link><LogoutButton/></div></section></main>}
function Detail({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="flex gap-3 text-sm text-slate-300"><span className="text-emerald-300 [&_svg]:size-5">{icon}</span><span><small className="block text-xs text-slate-500">{label}</small>{value}</span></div>}
