export type Coordinates={latitude:number;longitude:number};

const areas:Record<string,Coordinates>={lahore:{latitude:31.5204,longitude:74.3587},faisalabad:{latitude:31.4504,longitude:73.135},rawalpindi:{latitude:33.5651,longitude:73.0169},multan:{latitude:30.1575,longitude:71.5249},gujranwala:{latitude:32.1877,longitude:74.1945},sialkot:{latitude:32.4945,longitude:74.5229},bahawalpur:{latitude:29.3544,longitude:71.6911},sargodha:{latitude:32.074,longitude:72.6861},sheikhupura:{latitude:31.7167,longitude:73.985},kasur:{latitude:31.1187,longitude:74.4502},jhelum:{latitude:32.9405,longitude:73.7276},sahiwal:{latitude:30.6682,longitude:73.1114},gujrat:{latitude:32.5731,longitude:74.1005},"dera ghazi khan":{latitude:30.0489,longitude:70.6455}};

export function validCoordinates(latitude:number,longitude:number){return Number.isFinite(latitude)&&Number.isFinite(longitude)&&latitude>=-90&&latitude<=90&&longitude>=-180&&longitude<=180;}
export function parseCoordinate(value:unknown){if(typeof value==="number")return Number.isFinite(value)?value:Number.NaN;if(typeof value==="string"&&value.trim()!==""){const parsed=Number(value);return Number.isFinite(parsed)?parsed:Number.NaN;}return Number.NaN;}
export function coordinatesForArea(area:string|null|undefined){if(!area)return null;const normalized=area.trim().toLowerCase();return areas[normalized]??Object.entries(areas).find(([name])=>normalized.includes(name))?.[1]??null;}
export function canonicalArea(area:string|null|undefined){if(!area)return null;const normalized=area.trim().toLowerCase();const name=Object.keys(areas).find((candidate)=>normalized===candidate||normalized.includes(candidate));return name?name.replace(/\b\w/g,(letter)=>letter.toUpperCase()):null;}
export function distanceKm(origin:Coordinates,target:Coordinates){const radius=6371;const radians=(value:number)=>value*Math.PI/180;const dLat=radians(target.latitude-origin.latitude);const dLon=radians(target.longitude-origin.longitude);const a=Math.sin(dLat/2)**2+Math.cos(radians(origin.latitude))*Math.cos(radians(target.latitude))*Math.sin(dLon/2)**2;return radius*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
