import { NextResponse } from "next/server";
import { validRequestOrigin } from "@/lib/auth";
import { moderateMessage } from "@/lib/moderation";
import { requireVerifiedPublicUser } from "@/lib/public-auth";
import { createMatchMessageIfEligible, getPublicMatch, listMatchMessages, reserveMatchMessageQuota } from "@/lib/public-db";
import { validUuid } from "@/lib/security";

export const runtime="nodejs";
export async function GET(_request:Request,context:RouteContext<"/api/public/matches/[id]/messages">){try{const auth=await requireVerifiedPublicUser();if(!auth.user)return NextResponse.json({error:auth.error},{status:auth.status});const{id}=await context.params;if(!validUuid(id))return NextResponse.json({error:"Invalid match ID."},{status:400});const match=await getPublicMatch(auth.user.id,id);if(!match)return NextResponse.json({error:"Match not found."},{status:404});return NextResponse.json({match,messages:await listMatchMessages(id)});}catch(error){console.error("Unable to load match messages",error);return NextResponse.json({error:"Conversation could not be loaded."},{status:500});}}

export async function POST(request:Request,context:RouteContext<"/api/public/matches/[id]/messages">){if(!validRequestOrigin(request))return NextResponse.json({error:"Invalid request origin."},{status:403});try{const auth=await requireVerifiedPublicUser();if(!auth.user)return NextResponse.json({error:auth.error,blocked:auth.status===423},{status:auth.status});const{id}=await context.params;if(!validUuid(id))return NextResponse.json({error:"Invalid match ID."},{status:400});const match=await getPublicMatch(auth.user.id,id);if(!match)return NextResponse.json({error:"Match not found."},{status:404});if(match.medicalRecordId)return NextResponse.json({error:"Hospital-backed matches use the verified facility contact shown on this page."},{status:409});if(match.status!=="active")return NextResponse.json({error:"This conversation is closed."},{status:409});if(match.donorCooldownUntil&&new Date(match.donorCooldownUntil)>new Date())return NextResponse.json({error:"Messaging is paused during the donor's three-month blood donation cooldown."},{status:409});const parsed=await request.json().catch(()=>null);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))return NextResponse.json({error:"Enter a valid message."},{status:400});const content=String((parsed as Record<string,unknown>).content||"").trim().replace(/\s+/g," ").slice(0,800);if(!content)return NextResponse.json({error:"Enter a message."},{status:400});if(!await reserveMatchMessageQuota(id,auth.user.id))return NextResponse.json({error:"Message rate limit reached. Try again in one minute."},{status:429});const decision=await moderateMessage(content);if(decision.source==="local-fallback")return NextResponse.json({error:decision.reason},{status:503});const saved=await createMatchMessageIfEligible(id,auth.user.id,content,decision.allowed?"allowed":"blocked",decision.reason);if(!saved)return NextResponse.json({error:"The conversation changed while the message was being checked."},{status:409});if(!decision.allowed)return NextResponse.json({error:decision.reason||"The safety moderator blocked this message."},{status:422});return NextResponse.json({sent:true,moderatedBy:decision.source},{status:201});}catch(error){console.error("Unable to send match message",error);return NextResponse.json({error:"Message could not be sent."},{status:500});}}
