import { redirect } from "next/navigation";
import Link from "next/link";
import { BadgeCheck,CalendarDays,Clock3,Mail,MapPin,Phone,ShieldCheck,UserRound } from "lucide-react";
import { PublicLogoutButton } from "@/components/PublicLogoutButton";
import { getCurrentPublicUser } from "@/lib/public-auth";
import { emailVerificationIsCurrent } from "@/lib/verification";
export const dynamic="force-dynamic";
export default async function PublicProfilePage(){const user=await getCurrentPublicUser();if(!user)redirect("/public/login");if(user.status==="blocked")redirect("/public/blocked");if(!emailVerificationIsCurrent(user.emailVerifiedAt))redirect("/public/verify-email");const verificationUntil=new Date(new Date(user.emailVerifiedAt!).getTime()+7*86400000);return <main className="auth-page min-h-screen px-4 py-8 sm:px-6"><div className="mx-auto max-w-5xl"><header className="mb-6 flex items-center justify-between"><Link href="/public/dashboard" className="text-sm font-semibold text-emerald-300">← Public dashboard</Link><PublicLogoutButton/></header><section className="overflow-hidden rounded-[30px] border border-white/10 bg-[#071014]/90 shadow-2xl"><div className="border-b border-white/10 bg-[radial-gradient(circle_at_15%_20%,rgba(251,113,133,.16),transparent_35%),radial-gradient(circle_at_85%_80%,rgba(110,231,183,.14),transparent_40%)] p-7 sm:p-10"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="grid size-20 place-items-center rounded-2xl border border-rose-200/20 bg-rose-300/10 text-rose-200"><UserRound className="size-10"/></span><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold text-white">{user.name}</h1><span className="verified-badge"><BadgeCheck/> Email verified</span></div><p className="mt-2 text-slate-400">Protected public PHOTA account</p></div></div></div><div className="grid gap-4 p-5 sm:grid-cols-2 sm:p-8 lg:grid-cols-3"><Item icon={<Mail/>} label="Email" value={user.email}/><Item icon={<Phone/>} label="Phone" value={user.phone}/><Item icon={<CalendarDays/>} label="Age" value={`${user.age} years`}/><Item icon={<MapPin/>} label="Search area" value={user.area||"Set when searching"}/><Item icon={<ShieldCheck/>} label="Email valid until" value={verificationUntil.toLocaleDateString("en-PK",{dateStyle:"long"})}/><Item icon={<Clock3/>} label="Blood cooldown" value={user.cooldownUntil&&new Date(user.cooldownUntil)>new Date()?`Active until ${new Date(user.cooldownUntil).toLocaleDateString("en-PK",{dateStyle:"long"})}`:"No active cooldown"}/></div></section></div></main>}
function Item({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-2xl border border-white/8 bg-white/[.03] p-4"><span className="text-emerald-300 [&_svg]:size-5">{icon}</span><small className="mt-4 block text-xs uppercase tracking-wider text-slate-500">{label}</small><strong className="mt-1 block text-sm font-medium text-slate-200">{value}</strong></div>}
